### ISSUE TITLE
ejs exists

### ISSUE THREAD

**Issue by spotandjake** [selectthegang/glitchdex#16]
heyt select you should really use ejs instead of just all the code inside you index.js, also your tempalte literals are terrible and you should not string concentrate if you need help fixing just ask lol

**Comment by selectthegang** [comment]
we actually have been thinking about fixing that, but we don't know where exactly to start, if you want you can try and make a pull request

**Comment by alanlichen** [comment]
Ofc ejs exists, just it's sometimes annoying. 
The only thing I'm concerned about is the indents, vars, and template literals/string concatenation.

**Comment by alanlichen** [comment]
> we actually have been thinking about fixing that, but we don't know where exactly to start, if you want you can try and make a pull request

I could start it lol IDC  🤦‍♂️

**Comment by spotandjake** [comment]
yah i will take a look for you lol, and a crack, at it.

**Comment by selectthegang** [comment]
hmms
`console.log('err detected lol')`
